pipeline {
    agent any

    stages {
        stage('Test') {
            steps { 
                echo 'Testing...'
            }
        }
        stage('Allure reporting') {
            steps {
                echo 'Reporting goes here...'
            }
        }
    }

}